#!/bin/python3

import sys

n = int(input().strip())

# loop i from 1 to 10 not including 11
for i in range(1, 11):
    # print the formula in this format, n,i,n*i
	print('{0} x {1} = {2}'.format(n, i, n * i))
    
